version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - blog-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093" # For external access if needed
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - blog-network

  kafka-topics-creator:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka-topics-creator
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
              cub kafka-ready -b kafka:9092 1 20 && \
              kafka-topics --create --if-not-exists --topic post-events --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 && \
              kafka-topics --create --if-not-exists --topic user-events --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1'"
    depends_on:
      - kafka
    networks:
      - blog-network

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    image: blog-microservices_service-registry
    ports:
      - "8761:8761"
    networks:
      - blog-network

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: blog-microservices_config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    depends_on:
      - service-registry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - blog-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: blog-microservices_api-gateway
    depends_on:
      service-registry:
        condition: service_started
      config-server:
        condition: service_healthy
    networks:
      - blog-network

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    image: blog-microservices_users-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    depends_on:
      service-registry:
        condition: service_started
      config-server:
        condition: service_healthy
      postgres-users:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - blog-network

  posts-service:
    build:
      context: ./posts-service
      dockerfile: Dockerfile
    image: blog-microservices_posts-service
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    depends_on:
      service-registry:
        condition: service_started
      config-server:
        condition: service_healthy
      postgres-posts:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - blog-network

  postgres-users:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - blog-network

  postgres-posts:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Map to a different host port to avoid conflict
    networks:
      - blog-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      - blog-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - blog-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"  # OTLP gRPC port
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
