version: '3.8'
services:
  eureka-server:
    build: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - blog-network

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - blog-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    depends_on:
      - eureka-server
      - config-server
    networks:
      - blog-network

  users-service:
    build: ./users-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    depends_on:
      - eureka-server
      - config-server
      - postgres-users
    networks:
      - blog-network

  posts-service:
    build: ./posts-service
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    depends_on:
      - eureka-server
      - config-server
      - postgres-posts
    networks:
      - blog-network

  postgres-users:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - blog-network

  postgres-posts:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Map to a different host port to avoid conflict
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge