global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080', 'users-service:8081', 'posts-service:8082', 'service-registry:8761', 'config-server:8888']
