server:
  port: 8082

spring:
  application:
    name: posts-service
  jwt:
    secret: afafafafafafafafafafafafafafafafafafafafafafafafafafafafafafafaf
  datasource:
    url: jdbc:postgresql://postgres-posts:5432/postsdb
    driverClassName: org.postgresql.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: posts-service
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost