server:
  port: 8081

spring:
  application:
    name: users-service
  jwt:
    secret: afafafafafafafafafafafafafafafafafafafafafafafafafafafafafafafaf
    expiration: 3600000 # 1 hour in milliseconds
  datasource:
    url: jdbc:postgresql://postgres-users:5432/usersdb
    driverClassName: org.postgresql.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: users-service
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
